# Generated by Django 5.0.7 on 2024-07-14 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('membership', 'Membership'), ('upfront', 'Upfront Fees'), ('yearly', 'Yearly Fees')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iban', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator(message='Invalid IBAN format', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$')])),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bills', models.ManyToManyField(to='api.bill')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.investor')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.investor'),
        ),
    ]
