# Generated by Django 5.0.7 on 2024-07-16 10:57

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bill_fee_percentage_investor_amount_invested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalcall',
            name='iban',
            field=api.models.IBANField(max_length=34),
        ),
    ]
