# Generated by Django 5.0.7 on 2024-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_capitalcall_iban'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='capitalcall',
            name='status',
            field=models.CharField(choices=[('validated', 'Validated'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='validated', max_length=20),
        ),
        migrations.AlterField(
            model_name='investor',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
